### ISSUE TITLE
Status Bar fills with Indent Depth statuses

### ISSUE THREAD

**Issue by codeandcats** [SirTori/indenticator#1]
Indentictator seems to add multiple Indent Depth messages to the status bar:

![](http://s10.postimg.org/k2f8h7ltl/Screen_Shot_2016_09_22_at_8_17_05_AM.png)

**Comment by SirTori** [comment]
Thanks for the Feedback. I could reproduce the bug and fix it.
The fixed Version 0.2.1 has just been published to the marketplace

**Comment by codeandcats** [comment]
Nice job, thanks for the quick response. 👍
