### ISSUE TITLE
Line doesn't show if cursor is on an empty line

### ISSUE THREAD

**Issue by Srekel** [SirTori/indenticator#12]
See gif:

![vscode_indenticator](https://user-images.githubusercontent.com/1578924/28199405-ab7c13c2-6865-11e7-8a93-47cefac16d9f.gif)

**Comment by SirTori** [comment]
Sadly this is  a current limitation of the API provided to developers. see also #2

I am pretty sure it's the same reason [indent-rainbow](https://marketplace.visualstudio.com/items?itemName=oderwat.indent-rainbow) is having the same problem.

I'll keep an eye out for further options being provided by Microsoft, but i wouldn't hold my breath...

**Comment by Srekel** [comment]
Ok, sorry to hear that. If it ever changes, it'd be cool if you could comment on this so I could enable the plugin again. :)
