### ISSUE TITLE
Option to disable the dotted lines

### ISSUE THREAD

**Issue by steven7mwesigwa** [SirTori/indenticator#15]
Hi,
Is there a setting to _**disable**_ the _dotted lines_ but still have the vertical lines as guides? i.e;

_**From:**_

```
....|function() {
....|....console.log();
....|}
```

_**To;**_
```
    |function() {
    |    console.log();
    |}
```

**Comment by SirTori** [comment]
Sorry for the late response.

The dots are not a feature of this plugin, but of visual code itself.
The corresponding setting is "editor.renderWhitespace"
