### ISSUE TITLE
Highlights on wrong position

### ISSUE THREAD

**Issue by Mrkezii** [SirTori/indenticator#16]
Hi, Thanks for making this, as i installed it yesterday i noticed that the highlight doesn't work as expected for me, it seems to have some sort of offset.

See Screenshots, notice the position of the caret and the indent line. The caret and the indent lines are not in alignment.
<img width="650" alt="screen shot 2018-02-11 at 01 12 44" src="https://user-images.githubusercontent.com/13870224/36067938-2f3a94c2-0ec9-11e8-835b-ee34d9ee6b30.png">
<img width="789" alt="screen shot 2018-02-11 at 01 12 29" src="https://user-images.githubusercontent.com/13870224/36067939-2f6a2d36-0ec9-11e8-8a44-d8d078afcbe6.png">

**Comment by Hexodus** [comment]
I see the same problem here. The line is always on the previous indentation. Would be cool to at least be able to adjust this offset which isn't possible in the moment. ...but still a cool extension ;)

![indentbug](https://user-images.githubusercontent.com/243039/37244382-881b48f0-2488-11e8-8337-b6c9c0bf618c.jpg)

**Comment by SirTori** [comment]
@Mrkezii Thank you for bringing this to my attention. Unfortunately I couldn't replicate the issue. Can you maybe give me more details on how to reproduce it?

@Hexodus your suggestion falls more into line with #14 which has been implemented in release 0.5.0. If that does not satisfy your needs please feel free to open another issue detailing your desired behavior.
