### ISSUE TITLE
Uninstall should set IdentGuides back to what it was before install.

### ISSUE THREAD

**Issue by reidarkind** [SirTori/indenticator#22]
## Background
I installed the Indenticator extension. Didn't work as I expected with python, so I wanted to uninstalling it.

## Issue
After uninstalling I still had Indent guides in my editor, which wasn't there prior to the installation of Indenticator.

I then read that Indenticator sets the parameter `"editor.renderIndentGuides": true`.

## Request
Would be good if Indenticator reset `"editor.renderIndentGuides": false` if the value was `false` prior to the installation. 

Don't know if VS Code have any guidelines on what should be done when uninstalling an extension though.

**Comment by SirTori** [comment]
Hi,
sorry for the late response.

This extension does **not** set any settings for you. While I recommend setting `"editor.renderIndentGuides": true` I don't enforce it.
I don't even think it is possible for an extension to change your settings (and if it were possible I would think that it is a bad idea). Extensions can just add new settings and provide default values for those.
