### ISSUE TITLE
[Question] Don't show extra indent guides

### ISSUE THREAD

**Issue by lonix1** [SirTori/indenticator#24]
If a line has extra spaces, then it looks like this:

![73335621-97e38300-4278-11ea-9e55-f436f2469e79](https://user-images.githubusercontent.com/40320097/73336035-6fa85400-4279-11ea-8bc8-fb0b6ce2f474.png)

And that renders extra indent guides: `| | | | | | | | | | | | | | `. (I took an scss example, but it applies for any language).

Is there a way to prevent that?

**Comment by SirTori** [comment]
Hi,

Sorry for the late response. Even though I guess you have already figured this out, I'll wirte it down for others in the future:

These extra indent guides are the default ones of VS Code. If you don't want them you have to set the setting `editor.renderIndentGuides` (Editor: Render Indent Guides) to `false`.
I'll add a reference to this setting to the README in the next release.

**Comment by lonix1** [comment]
I'm a little confused: if I set that won't it disable ALL indent guides, including yours?

**Comment by SirTori** [comment]
`editor.renderIndentGuides` only controls the built-in indent guides of visual studio code. They are completely independent of the ones added by this extension.

Visual Studio Code has two kinds of built-in Indent guides:
`editor.renderIndentGuides`: Renders a thin line on *every* indent step
`editor.highlightActiveIndentGuide`: Highlights the highest indent on the current cursor position

This extension adds up to two further indent highlights:
`indenticator.showHighlight`: Highlights the indent depth enclosing the current cursor position
`indenticator.inner.showHighlight`: Highlights the indent depth enclosed by the current cursor position

See the Remarks (https://github.com/SirTori/indenticator#remarks) in the Readme for a visual aid explaining the different highlights

**Comment by lonix1** [comment]
Thanks that is very helpful!
